engine/configurations/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf import settings

from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [
    url(r'^', include("engine.pages.common.urls")),
    url(r'^channels/', include("engine.pages.channel.urls"))
]

if "static" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^pages/', include("engine.pages.static.urls")))

if "upload" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^files/', include("engine.pages.upload.urls")))

if "server" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^servers/', include("engine.pages.server.urls")))

if "game" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^games/', include("engine.pages.game.urls")))

if "calendar" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^calendar/', include("engine.pages.calendar.urls")))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/pages/game/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf.urls import url
from django.conf.urls import include

# Pebble
from engine.pages.game.views import GameView

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [

    # ----------------------------------------
    #   Actions
    # ----------------------------------------

    url(r'^action/game/', include([
        url(r'^add/$',
            GameView.add, name="action_game_add"),
        url(r'^edit/(?P<game_id>[\d]+)/$',
            GameView.edit, name="action_game_edit"),
        url(r'^delete/(?P<game_id>[\d]+)/$',
            GameView.delete, name="action_game_delete"),
        url(r'^page/$',
            GameView.page, name="action_game_page"),
        url(r'^register/(?P<game_id>[\d]+)/$',
            GameView.register, name="action_game_register")
        ])
    ),

    # ----------------------------------------
    #   Views
    # ----------------------------------------

    url(r'^$',
        GameView.index, name="game_home"),

    url(r'^random/$',
        GameView.random, name="game_random"),

    url(r'^(?P<page>\d+)/$',
        GameView.index, name="game_page"),

    url(r'^(?P<identifier>[^\s\/]+)-(?P<index>[\d]+)/$',
        GameView.view, name="game_look")
]

engine/pages/game/models.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.db import models

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator

from django.contrib.auth.models import User

# Pebble
from engine.pages.server.models import Server

# ------------------------------------------------------------------------------
#   Models
# ------------------------------------------------------------------------------

class Platform(models.Model):

    type = "platform"

    title = models.CharField(max_length=256)

    icon = models.CharField(max_length=256, blank=True)

    identifier = models.CharField(max_length=512)


    def __str__(self):
        """ Return model representation

        Returns
        -------
        str
            Model as string
        """

        return self.title


class Distributor(models.Model):

    type = "distributor"

    title = models.CharField(max_length=256)

    identifier = models.CharField(max_length=512)

    icon = models.CharField(max_length=256, blank=True)

    website = models.URLField(blank=True)


    def __str__(self):
        """ Return model representation

        Returns
        -------
        str
            Model as string
        """

        return self.title


class Game(models.Model):

    type = "game"

    title = models.CharField(max_length=256)

    identifier = models.CharField(max_length=512)

    description = models.TextField(blank=True)

    hostable = models.BooleanField(default=False)

    website = models.URLField(blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    platforms = models.ManyToManyField(
        Platform, related_name="game_platforms", blank=True)
    distributors = models.ManyToManyField(
        Distributor, related_name="game_distributors", blank=True)
    users = models.ManyToManyField(
        User, related_name="game_users", blank=True)

    server = models.ForeignKey(
        Server, blank=True, null=True, related_name="game_updater")
    updater = models.ForeignKey(
        User, blank=True, null=True, related_name="game_updater")


    def __str__(self):
        """ Return model representation

        Returns
        -------
        str
            Model as string
        """

        if self.updater is not None:
            return "%s updated by %s" % (self.title, self.updater.username)

        return self.title

engine/pages/game/views.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django import forms

from django.conf import settings

from django.urls import reverse

from django.http import HttpResponseRedirect

from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext as _

# Pebble
from engine.common import generate_identifier

from engine.pages.channel.models import Channel
from engine.pages.server.models import Server
from engine.pages.game.models import Game

# Random
from random import randint

# ------------------------------------------------------------------------------
#   Forms
# ------------------------------------------------------------------------------

class GameForm(forms.ModelForm):

    class Meta:

        model = Game

        fields = [
            "hostable",
            "title",
            "server",
            "website",
            "platforms",
            "distributors",
            "description"
        ]

# ------------------------------------------------------------------------------
#   Views
# ------------------------------------------------------------------------------

class GameView(object):

    @login_required()
    def index(request, page=None):
        """ List available games

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        page : int or None, optional
            Games list paginator index
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        paginator = Paginator(Game.objects.order_by("title"),
            settings.PAGES["game"])

        # Load topics for specified page
        try:
            games = paginator.page(page)

        except PageNotAnInteger as error:
            games = paginator.page(1)

        except EmptyPage as error:
            games = paginator.page(paginator.num_pages)

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "game/index.html", {
            "page": "games",
            "user": login,
            "games": games
        })


    @login_required()
    def random(request):
        """ Show a random game from database storage

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        games = Game.objects.filter(users__pk=login.pk)

        if len(games) > 0:
            game = randint(1, len(games))

            return HttpResponseRedirect(reverse("game_look",
                args=( games[game - 1].identifier, games[game - 1].pk )))

        return HttpResponseRedirect(reverse("game_home"))


    @login_required()
    def page(request):
        """ Move to a specific page

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        page = None

        if request.method == "POST":
            page = int(request.POST["page"])

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return HttpResponseRedirect(
            reverse("game_page", args=( page, )))


    @login_required()
    def register(request, game_id):
        """ Register to a specific game

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        game_id : int
            Page primary key identifier
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        game = get_object_or_404(Game, pk=game_id)

        if not login in game.users.all():
            game.users.add(login)

        else:
            game.users.remove(login)

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return HttpResponseRedirect(
            reverse("game_look", args=( game.identifier, game.pk )))


    @login_required()
    def view(request, identifier, index):
        """ View a specific game

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        identifier : str
            Game identifier
        index : int
            Game index
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        game = get_object_or_404(Game, pk=index)

        # Avoid to list unactive users
        game.users = game.users.exclude(is_active=False)

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "game/view.html", {
            "page": "games",
            "user": login,
            "game": game
        })


    @login_required()
    def add(request):
        """ Add a new game

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        if not login.has_perm("game.add_game"):
            return HttpResponseRedirect(reverse("error"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        if request.method == "POST":
            form = GameForm(request.POST)

            if form.is_valid():
                game = Game()

                game.title = form.cleaned_data["title"]
                game.server = form.cleaned_data["server"]
                game.website = form.cleaned_data["website"]
                game.hostable = form.cleaned_data["hostable"]
                game.description = form.cleaned_data["description"]
                game.identifier = generate_identifier(game.title)
                game.updater = login

                game.save()

                game.platforms = form.cleaned_data["platforms"]
                game.distributors = form.cleaned_data["distributors"]

                game.save()

                return HttpResponseRedirect(reverse("game_look",
                    args=( game.identifier, game.pk )))

        else:
            form = GameForm(initial={ "updater": login.pk })

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "game/edit.html", {
            "page": "games",
            "user": login,
            "form": form
        })


    @login_required()
    def edit(request, game_id):
        """ Edit an existing game

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        game_id : int
            Page primary key identifier
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        if not login.has_perm("game.change_game"):
            return HttpResponseRedirect(reverse("error"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        game = get_object_or_404(Game, pk=game_id)

        if request.method == "POST":
            form = GameForm(request.POST)

            if form.is_valid():
                form.cleaned_data["updater"] = login

                for key, value in form.cleaned_data.items():
                    setattr(game, key, value)

                # Generate game identifier
                game.identifier = generate_identifier(game.title)

                game.save()

                return HttpResponseRedirect(reverse("game_look",
                    args=( game.identifier, game.pk )))

templates/game/delete.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} - {% trans 'Remove game' %} - {{ game.title }}{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-trash"></i>
                    {% trans 'Remove game' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'game_look' game.identifier game.pk %}" title="{% trans 'Back to game' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                    </ul>
                </nav>
            </header>

            <aside>
                <div class="banner warning">
                    {% blocktrans with title=game.title %}Are you sure to remove '{{ title }}' game ?{% endblocktrans %}
                </div>

                <form method="post" class="delete">
                    {% csrf_token %}

                    <div class="inline">
                        <input type="radio" id="radio_no" name="choice" value="no" checked="checked" />&nbsp;
                        <label class="left" for="radio_no">{% trans 'No' %}</label>
                    </div>

                    <div class="inline">
                        <input type="radio" id="radio_yes" name="choice" value="yes" />&nbsp;
                        <label class="left" for="radio_yes">{% trans 'Yes' %}</label>
                    </div>

                    <footer>
                        <input class="destructive-action" type="submit" value="{% trans 'Remove' %}" />
                    </footer>
                </form>
            </aside>
        </article>
{% endblock %}

templates/game/edit.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} -
    {% if game %}
        {% trans 'Edit game' %} - {{ game.title }}
    {% else %}
        {% trans 'New game' %}
    {% endif %}
{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    {% if game %}
                    <i class="fa fa-fw fa-edit"></i>
                    {% trans 'Edit game' %}
                    {% else %}
                    <i class="fa fa-fw fa-plus-square"></i>
                    {% trans 'New game' %}
                    {% endif %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            {% if game %}
                            <a href="{% url 'game_look' game.identifier game.pk %}" title="{% trans 'Back to game' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                            {% else %}
                            <a href="{% url 'game_home' %}" title="{% trans 'Back to games' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                            {% endif %}
                        </li>
                    {% if game and user.is_staff %}
                        <li class="destructive-action">
                            <a href="{% url 'action_game_delete' game.pk %}" title="{% trans 'Remove' %}">
                                <i class="fa fa-fw fa-remove"></i></a>
                        </li>
                    {% endif %}
                    </ul>
                </nav>
            </header>

            <aside>
                <form method="post">
                    {% csrf_token %}

                    <div class="inline">
                        {{ form.hostable }}
                        <label for="id_hostable">{% trans 'Hostable' %}</label>
                    </div>

                    <div>
                        <label for="id_title">{% trans 'Title' %}&nbsp;:</label>
                        {{ form.title }}
                    </div>

                    <div>
                        <label for="id_website">{% trans 'Website' %}&nbsp;:</label>
                        {{ form.website }}
                    </div>

                    <div>
                        <label for="id_description">{% trans 'Description' %}&nbsp;:</label>
                        {{ form.description }}
                    </div>

                    <div>
                        <label for="id_platforms">{% trans 'Platforms' %}&nbsp;:</label>
                        {{ form.platforms }}
                    </div>

                    <div>
                        <label for="id_distributors">{% trans 'Distributors' %}&nbsp;:</label>
                        {{ form.distributors }}
                    </div>

                    <div>
                        <label for="id_server">{% trans 'Server' %}&nbsp;:</label>
                        {{ form.server }}
                    </div>

                    <footer>
                        {% if game %}
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                        {% else %}
                        <input class="important" type="submit" value="{% trans 'Create' %}" />
                        {% endif %}
                    </footer>
                </form>
            </aside>
        </article>
{% endblock %}

templates/game/index.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} - {% trans 'Games list' %}{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-gamepad"></i>
                    {% trans 'Games' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="" title="{% trans 'Random game' %}">
                                <i class="fa fa-fw fa-random"></i></a>
                        </li>
                        {% if perms.game.add_game %}
                        <li class="creative-action">
                            <a href="{% url 'action_game_add' %}" title="{% trans 'New game' %}">
                                <i class="fa fa-fw fa-plus"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </header>

            {% if games|length > 0 %}
            <aside class="table">
                {% for game in games %}
                <div class="big">
                    <span>
                        {% if game.hostable %}
                        <i class="fa fa-fw fa-server"></i>
                        {% else %}
                        <i class="fa fa-fw fa-cloud"></i>
                        {% endif %}
                    </span>

                    <span class="full-size">
                        <a href="{% url 'game_look' game.identifier game.pk %}"
                            title="{{ game.summary }}">
                            {{ game.title }}
                        </a>
                    </span>

                    <span class="nowrap right">
                    {% for player in game.users.all|dictsort:"username" %}
                        {% if player.is_active %}
                        <a href="{% url 'profile' player.username %}">
                            <img class="avatar big" title="{{ player.username }}"
                                src="{{ player.informations.avatar.url|avatar }}" />
                        </a>
                        {% endif %}
                    {% endfor %}
                    </span>
                </div>
                {% endfor %}
            </aside>
            {% else %}
            <div class="banner warning">
                {% trans 'No game available' %}
            </div>
            {% endif %}
        </article>

        {% if games.paginator.num_pages > 1 %}
        <nav class="pagination">
            <ul>
                <li>
                    {% if games.has_previous %}
                    <a href="{% url 'game_page' 1 %}">
                        <i class="fa fa-chevron-left space"></i>{% trans 'First' %}
                    </a>
                    {% else %}
                    <div>
                        <i class="fa fa-chevron-left space"></i>{% trans 'First' %}
                    </div>
                    {% endif %}
                </li>
                <li>
                    {% if games.has_previous %}
                    <a href="{% url 'game_page' games.previous_page_number %}">
                        <i class="fa fa-caret-left space"></i>{% trans 'Previous' %}
                    </a>
                    {% else %}
                    <div>
                        <i class="fa fa-caret-left space"></i>{% trans 'Previous' %}
                    </div>
                    {% endif %}
                </li>
                <li class="selector">
                    <form action="{% url 'action_game_page' %}" method="post">
                        {% csrf_token %}

                        <label for="page">{% trans 'Move to page' %}</label>
                        <select name="page" id="page">
                            {% for index in games.paginator.page_range %}
                            <option {% if index == games.number %}selected="selected"{% endif %}
                                value="{{ index }}">{{ index }}</option>
                            {% endfor %}
                        </select>

                        <input type="submit" name="valid" value="Go" id="valid" />
                    </form>
                </li>
                <li>
                    {% if games.has_next %}
                    <a href="{% url 'game_page' games.next_page_number %}">
                        {% trans 'Next' %}<i class="fa fa-caret-right anti-space"></i>
                    </a>
                    {% else %}
                    <div>
                        {% trans 'Next' %}<i class="fa fa-caret-right anti-space"></i>
                    </div>
                    {% endif %}
                </li>
                <li>
                    {% if games.has_next %}
                    <a href="{% url 'game_page' games.paginator.num_pages %}">
                        {% trans 'Last' %}<i class="fa fa-chevron-right anti-space"></i>
                    </a>
                    {% else %}
                    <div>
                        {% trans 'Last' %}<i class="fa fa-chevron-right anti-space"></i>
                    </div>
                    {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
{% endblock %}

templates/game/sidebar.html
{% load utils i18n %}
                        <li {% if page == 'games' %}class="active"{% endif %}>
                            <a href="{% url 'game_home' %}">
                                {% trans 'Games' %}
                            </a>
                            <a href="{% url 'game_random' %}" title="{% trans 'Random game' %}">
                                <i class="fa fa-fw fa-random normal-action"></i>
                            </a>
                            {% if perms.game.add_game %}
                            <a href="{% url 'action_game_add' %}" title="{% trans 'Add game' %}">
                                <i class="fa fa-fw fa-plus creative-action"></i>
                            </a>
                            {% endif %}
                        </li>