engine/configurations/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf import settings

from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [
    url(r'^', include("engine.pages.common.urls")),
    url(r'^channels/', include("engine.pages.channel.urls"))
]

if "static" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^pages/', include("engine.pages.static.urls")))

if "upload" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^files/', include("engine.pages.upload.urls")))

if "server" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^servers/', include("engine.pages.server.urls")))

if "game" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^games/', include("engine.pages.game.urls")))

if "calendar" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^calendar/', include("engine.pages.calendar.urls")))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/pages/upload/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf.urls import url
from django.conf.urls import include

# Pebble
from engine.pages.upload.views import UploadView
from engine.pages.upload.views import PrivateView

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [

    # ----------------------------------------
    #   Actions
    # ----------------------------------------

    url(r'^action/', include([
        url(r'^add/$',
            UploadView.add, name="action_upload_add"),
        url(r'^edit/(?P<file_id>[\d]+)/$',
            UploadView.edit, name="action_upload_edit"),
        url(r'^delete/(?P<file_id>[\d]+)/$',
            UploadView.delete, name="action_upload_delete"),
        url(r'^page/$',
            UploadView.page, name="action_upload_page")
        ])
    ),

    # ----------------------------------------
    #   Views
    # ----------------------------------------

    url(r'^$',
        UploadView.index, name="upload_home"),

    url(r'^privates/$',
        PrivateView.index, name="private_home"),

    url(r'^privates/(?P<page>\d+)/$',
        PrivateView.index, name="private_page"),

    url(r'^(?P<page>\d+)/$',
        UploadView.index, name="upload_page"),

    url(r'^(?P<identifier>[^\s\/]+)-(?P<index>[\d]+)/$',
        UploadView.view, name="upload_look")
]

engine/pages/upload/models.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.db import models

from django.conf import settings

from django.contrib.auth.models import User

from os import remove

from pathlib import Path

# Pebble
from engine.common import is_allowed
from engine.common import get_mimetype
from engine.common import generate_identifier

# ------------------------------------------------------------------------------
#   Functions
# ------------------------------------------------------------------------------

def upload_data(instance, filename):
    """ Upload an avatar

    This function define the user avatar file and replace the existing one

    Parameters
    ----------
    instance : upload.models.File
        Database object instance
    filename : str
        New filename

    Returns
    -------
    str
        New avatar path in upload directory
    """

    extension = settings.ALLOWED_EXTENSIONS[instance.mimetype]

    # Generate a hash based on object identifier
    try:
        from hashlib import blake2b

        name = blake2b(digest_size=32)

    except ImportError:
        from hashlib import sha256

        name = sha256()

    name.update(bytes(instance.identifier, "UTF-8"))

    path = Path("file", "%s.%s" % (name.hexdigest(), extension))

    # Save file to uploads folder
    media_path = Path(settings.MEDIA_ROOT)

    # Replace an existing file
    if media_path.joinpath(path).exists():
        media_path.joinpath(path).unlink()

    return path

# ------------------------------------------------------------------------------
#   Models
# ------------------------------------------------------------------------------

class File(models.Model):

    type = "file"

    title = models.CharField(max_length=256)

    identifier = models.CharField(max_length=512)

    description = models.CharField(max_length=500, blank=True)

    mimetype = models.CharField(max_length=512)

    private = models.BooleanField(default=False)

    path = models.FileField(upload_to=upload_data)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="file_user")


    def __str__(self):
        """ Return model representation

        Returns
        -------
        str
            Model as string
        """

        return "%s by %s" % (self.title, self.user.username)


    def __remove(self):
        """ Remove file from upload folder
        """

        path = Path(str(self.path))

        media_path = Path(settings.MEDIA_ROOT)

        if media_path.joinpath(path).exists():
            media_path.joinpath(path).unlink()


    def save(self):
        """ Save model and his data
        """

        # Generate a new identifier
        self.identifier = generate_identifier(self.title)

        # Read mimetype from uploaded file
        mime = get_mimetype(self.path.file)

        if not mime == "application/x-empty":

            # Avoid to upload unauthorized extensions
            if not is_allowed(mime):
                raise TypeError("Unauthorized mimetype")

            setattr(self, "mimetype", mime)

        super(File, self).save()


    def delete(self):
        """ Delete model and his data
        """

        self.__remove()

        super(File, self).delete()


    def replace(self, path):
        """ Replace previous file and remove it from disk

        Parameters
        ----------
        path : django.core.files.uploadedfile.InMemoryUploadedFile
            New file instance
        """

        if len(str(self.path)) > 0:
            self.__remove()

        setattr(self, "path", path)

templates/upload/delete.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} - {% trans 'Remove file' %} - {{ upload.title }}{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-trash"></i>
                    {% trans 'Remove file' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'upload_look' upload.identifier upload.pk %}" title="{% trans 'Back to file' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                    </ul>
                </nav>
            </header>

            <aside>
                <div class="banner warning">
                    {% blocktrans with title=upload.title %}Are you sure to remove '{{ title }}' file ?{% endblocktrans %}
                </div>

                <form method="post" class="delete">
                    {% csrf_token %}

                    <div class="inline">
                        <input type="radio" id="radio_no" name="choice" value="no" checked="checked" />&nbsp;
                        <label class="left" for="radio_no">{% trans 'No' %}</label>
                    </div>

                    <div class="inline">
                        <input type="radio" id="radio_yes" name="choice" value="yes" />&nbsp;
                        <label class="left" for="radio_yes">{% trans 'Yes' %}</label>
                    </div>

                    <footer>
                        <input class="destructive-action" type="submit" value="{% trans 'Remove' %}" />
                    </footer>
                </form>
            </aside>
        </article>
{% endblock %}

templates/upload/edit.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} -
    {% if upload %}
        {% trans 'Edit file' %} - {{ upload.title }}
    {% else %}
        {% trans 'New file' %}
    {% endif %}
{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    {% if upload %}
                    <i class="fa fa-fw fa-edit"></i>
                    {% trans 'Edit file' %}
                    {% else %}
                    <i class="fa fa-fw fa-plus-square"></i>
                    {% trans 'New file' %}
                    {% endif %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            {% if upload %}
                            <a href="{% url 'upload_look' upload.identifier upload.pk %}" title="{% trans 'Back to file' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                            {% else %}
                            <a href="{% url 'upload_home' %}" title="{% trans 'Back to files' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                            {% endif %}
                        </li>
                    {% if upload and perms.upload.delete_file %}
                        {% if user.pk == upload.user.pk or user.is_staff %}
                        <li class="destructive-action">
                            <a href="{% url 'action_upload_delete' upload.pk %}" title="{% trans 'Remove' %}">
                                <i class="fa fa-fw fa-remove"></i></a>
                        </li>
                        {% endif %}
                    {% endif %}
                    </ul>
                </nav>
            </header>

            {% if messages %}
            <aside class="banners">
                <ul class="messages">
                    {% for message in messages %}
                    <li>
                        <div{% if message.tags %} class="banner {{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </aside>
            {% endif %}

            <aside>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="inline">
                        {{ form.private }}
                        <label for="id_private">{% trans 'Private' %}</label>
                    </div>

                    <div>
                        <label for="id_title">{% trans 'Title' %}&nbsp;:</label>
                        {{ form.title }}
                    </div>

                    <div>
                        <label for="id_description">{% trans 'Description' %}&nbsp;:</label>
                        {{ form.description }}
                    </div>

                    <div>
                        <label for="id_path">{% trans 'File path' %}&nbsp;:</label>
                        {{ form.path }}
                    </div>

                    <footer>
                        {% if upload %}
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                        {% else %}
                        <input class="important" type="submit" value="{% trans 'Create' %}" />
                        {% endif %}
                    </footer>
                </form>
            </aside>
        </article>
{% endblock %}

templates/upload/index.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} -
    {% if page == "files" %}
        {% trans 'Files list' %}
    {% else %}
        {% trans 'My files' %}
    {% endif %}
{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    {% if page == "files" %}
                    <i class="fa fa-fw fa-folder"></i>
                    {% trans 'Files' %}
                    {% else %}
                    <i class="fa fa-fw fa-lock"></i>
                    {% trans 'My files' %}
                    {% endif %}
                </h1>

                {% if perms.upload.add_file %}
                <nav>
                    <ul>
                        <li class="custom-action">
                            {% if page == "files" %}
                            <a href="{% url 'private_home' %}" title="{% trans 'My files' %}">
                                <i class="fa fa-fw fa-lock"></i></a>
                            {% else %}
                            <a href="{% url 'upload_home' %}" title="{% trans 'Files' %}">
                                <i class="fa fa-fw fa-folder"></i></a>
                            {% endif %}
                        </li>
                        <li class="creative-action">
                            <a href="{% url 'action_upload_add' %}" title="{% trans 'New upload' %}">
                                <i class="fa fa-fw fa-plus"></i></a>
                        </li>
                    </ul>
                </nav>
                {% endif %}
            </header>

            {% if files|length > 0 %}
            <aside class="table">
                {% for file in files %}
                <div class="big">
                    <span class="full-size">
                        <a href="{% url 'upload_look' file.identifier file.pk %}"
                            title="{{ file.description }}">
                            {{ file.title }}
                        </a>
                    </span>

                    <span class="nowrap">
                        {% if "audio/" in file.mimetype %}
                        <i class="fa fa-fw fa-file-audio-o green"></i>
                        <small>{% trans 'Audio' %}</small>
                        {% elif "image/" in file.mimetype %}
                        <i class="fa fa-fw fa-file-image-o blue"></i>
                        <small>{% trans 'Image' %}</small>
                        {% elif "video/" in file.mimetype %}
                        <i class="fa fa-fw fa-file-video-o magenta"></i>
                        <small>{% trans 'Video' %}</small>
                        {% elif "text/" in file.mimetype %}
                        <i class="fa fa-fw fa-file-text-o cyan"></i>
                        <small>{% trans 'Text' %}</small>
                        {% elif file.mimetype == "application/pdf" %}
                        <i class="fa fa-fw fa-file-pdf-o red"></i>
                        <small>{% trans 'PDF' %}</small>
                        {% endif %}
                    </span>

                    <span class="nowrap">
                        <i class="fa fa-fw fa-calendar"></i>
                        <small>
                        {% if file.updated|istoday %}
                            <strong>{{ file.updated|prettydate }}</strong>
                        {% else %}
                            {{ file.updated|prettydate }}
                        {% endif %}
                        </small>
                    </span>

                    <span>
                        <a href="{% url 'profile' file.user.username %}">
                            <img class="avatar big" title="{{ file.user.username }}"
                                src="{{ file.user.informations.avatar.url|avatar }}" />
                        </a>
                    </span>
                </div>
                {% endfor %}
            </aside>
            {% else %}
            <div class="banner warning">
                {% trans 'No file available' %}
            </div>
            {% endif %}
        </article>

        {% if files.paginator.num_pages > 1 %}
        <nav class="pagination">
            <ul>
                <li>
                    {% if files.has_previous %}
                    <a href="{% url 'upload_page' 1 %}">
                        <i class="fa fa-chevron-left space"></i>{% trans 'First' %}
                    </a>
                    {% else %}
                    <div>
                        <i class="fa fa-chevron-left space"></i>{% trans 'First' %}
                    </div>
                    {% endif %}
                </li>
                <li>
                    {% if files.has_previous %}
                    <a href="{% url 'upload_page' files.previous_page_number %}">
                        <i class="fa fa-caret-left space"></i>{% trans 'Previous' %}
                    </a>
                    {% else %}
                    <div>
                        <i class="fa fa-caret-left space"></i>{% trans 'Previous' %}
                    </div>
                    {% endif %}
                </li>
                <li class="selector">
                    <form action="{% url 'action_upload_page' %}" method="post">
                        {% csrf_token %}

                        <label for="page">{% trans 'Move to page' %}</label>
                        <select name="page" id="page">
                            {% for index in files.paginator.page_range %}
                            <option {% if index == files.number %}selected="selected"{% endif %}
                                value="{{ index }}">{{ index }}</option>
                            {% endfor %}
                        </select>

                        <input type="submit" name="valid" value="Go" id="valid" />
                    </form>
                </li>
                <li>
                    {% if files.has_next %}
                    <a href="{% url 'upload_page' files.next_page_number %}">
                        {% trans 'Next' %}<i class="fa fa-caret-right anti-space"></i>
                    </a>
                    {% else %}
                    <div>
                        {% trans 'Next' %}<i class="fa fa-caret-right anti-space"></i>
                    </div>
                    {% endif %}
                </li>
                <li>
                    {% if files.has_next %}
                    <a href="{% url 'upload_page' files.paginator.num_pages %}">
                        {% trans 'Last' %}<i class="fa fa-chevron-right anti-space"></i>
                    </a>
                    {% else %}
                    <div>
                        {% trans 'Last' %}<i class="fa fa-chevron-right anti-space"></i>
                    </div>
                    {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
{% endblock %}

templates/upload/sidebar.html
{% load utils i18n %}
                        <li {% if page == 'files' %}class="active"{% endif %}>
                            <a href="{% url 'upload_home' %}">
                                {% trans 'Files' %}
                            </a>
                            {% if perms.upload.add_file %}
                            <a href="{% url 'private_home' %}" title="{% trans 'My files' %}">
                                <i class="fa fa-fw fa-lock custom-action"></i>
                            </a>
                            <a href="{% url 'action_upload_add' %}" title="{% trans 'Add file' %}">
                                <i class="fa fa-fw fa-plus creative-action"></i>
                            </a>
                            {% endif %}
                        </li>

templates/upload/view.html
{% extends "base.html" %}

{% load utils i18n static %}

{% block title %} - {% trans 'File' %} - {{ file.title }}{% endblock %}

{% block main %}
        <article class="upload">
            <header>
                <h1>
                    {% if "audio/" in file.mimetype %}
                    <i class="fa fa-fw fa-file-audio-o"></i>
                    {% elif "image/" in file.mimetype %}
                    <i class="fa fa-fw fa-file-image-o"></i>
                    {% elif "video/" in file.mimetype %}
                    <i class="fa fa-fw fa-file-video-o"></i>
                    {% elif "text/" in file.mimetype %}
                    <i class="fa fa-fw fa-file-text-o"></i>
                    {% elif file.mimetype == "application/pdf" %}
                    <i class="fa fa-fw fa-file-pdf-o"></i>
                    {% endif %}
                    {{ file.title }}
                </h1>

                <nav>
                    <ul>
                        <li>
                        {% if file.private %}
                            <a href="{% url 'private_home' %}" title="{% trans 'Back to private files' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        {% else %}
                            <a href="{% url 'upload_home' %}" title="{% trans 'Back to files' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        {% endif %}
                        </li>
                    {% if perms.upload.change_file %}
                        {% if user.pk == file.user.pk or user.is_staff %}
                        <li>
                            <a href="{% url 'action_upload_edit' file.pk %}" title="{% trans 'Edit' %}">
                                <i class="fa fa-fw fa-cog"></i></a>
                        </li>
                        {% endif %}
                    {% endif %}
                        <li class="custom-action">
                            <a href="{% get_media_prefix %}{{ file.path }}" title="{% trans 'Download' %}">
                                <i class="fa fa-fw fa-download"></i></a>
                        </li>
                    {% if perms.upload.delete_file %}
                        {% if user.pk == file.user.pk or user.is_staff %}
                        <li class="destructive-action">
                            <a href="{% url 'action_upload_delete' file.pk %}" title="{% trans 'Remove' %}">
                                <i class="fa fa-fw fa-remove"></i></a>
                        </li>
                        {% endif %}
                    {% endif %}
                    </ul>
                </nav>
            </header>

            <aside class="upload">
                <div class="center">
                {% if "image/" in file.mimetype %}
                    ​<picture>
                        <source srcset="{% get_media_prefix %}{{ file.path }}" type="{{ file.mimetype }}">
                        <img src="{% get_media_prefix %}{{ file.path }}" alt="{{ file.description }}">
                    </picture>
                {% elif "video/" in file.mimetype %}
                    <video controls>
                        <source src="{% get_media_prefix %}{{ file.path }}" type="{{ file.mimetype }}">
                        <p>Your browser doesn't support HTML5 video.</p>
                    </video>
                {% elif "audio/" in file.mimetype %}
                    <audio controls>
                        <source src="{% get_media_prefix %}{{ file.path }}" type="{{ file.mimetype }}">
                        <p>Your browser doesn't support HTML5 audio.</p>
                    </audio>
                {% else %}
                    <span class="button custom-action">
                        <a href="{% get_media_prefix %}{{ file.path }}" title="{% trans 'Download' %}">
                            <i class="fa fa-4x fa-download"></i></a>
                    </span>
                {% endif %}
                </div>
            </aside>

            {% if file.description %}
            <aside class="description center">
                {{ file.description }}
            </aside>
            {% endif %}

            <aside>
                <div>
                    <strong>{% trans 'Direct link' %}</strong>
                    <input type="text" class="full-size" value="{% get_media_prefix %}{{ file.path }}" />
                </div>
                <div>
                    <strong>{% trans 'HTML' %}</strong>
                    {% if "image/" in file.mimetype %}
                    <input type="text" class="full-size"
                        value="​<img src='{% get_media_prefix %}{{ file.path }}' alt='{% if file.description %}{{ file.description }}{% else %}{{ file.title }}{% endif %}'>" />
                    {% else %}
                    <input type="text" class="full-size"
                        value="<a href='{% get_media_prefix %}{{ file.path }}' alt='{% if file.description %}{{ file.description }}{% else %}{{ file.title }}{% endif %}'>{{ file.title }}</a>" />
                    {% endif %}
                </div>
                <div>
                    <strong>{% trans 'HTML 5' %}</strong>
                    {% if "image/" in file.mimetype %}
                    <input type="text" class="full-size"
                        value="​<picture><source srcset='{% get_media_prefix %}{{ file.path }}' type='{{ file.mimetype }}'><img src='{% get_media_prefix %}{{ file.path }}' alt='{% if file.description %}{{ file.description }}{% else %}{{ file.title }}{% endif %}'></picture>" />
                    {% elif "video/" in file.mimetype %}
                    <input type="text" class="full-size"
                        value="<video controls><source src='{% get_media_prefix %}{{ file.path }}' type='{{ file.mimetype }}'><p>Your browser doesn't support HTML5 video.</p></video>" />
                    {% elif "audio/" in file.mimetype %}
                    <input type="text" class="full-size"
                        value="<audio controls><source src='{% get_media_prefix %}{{ file.path }}' type='{{ file.mimetype }}'><p>Your browser doesn't support HTML5 audio.</p></audio>" />
                    {% elif "text/" in file.mimetype %}
                    <input type="text" class="full-size"
                        value="<a href='{% get_media_prefix %}{{ file.path }}' alt='{% if file.description %}{{ file.description }}{% else %}{{ file.title }}{% endif %}'>{{ file.title }}</a>" />
                    {% elif file.mimetype == "application/pdf" %}
                    <input type="text" class="full-size"
                        value="<a href='{% get_media_prefix %}{{ file.path }}' alt='{% if file.description %}{{ file.description }}{% else %}{{ file.title }}{% endif %}'>{{ file.title }}</a>" />
                    {% endif %}
                </div>
                <div>
                    <strong>{% trans 'Markdown' %}</strong>
                    {% if "image/" in file.mimetype %}
                    <input type="text" class="full-size"
                        value='![{% if file.description %}{{ file.description }}{% else %}{{ file.title }}{% endif %}]({% get_media_prefix %}{{ file.path }} "{{ file.title }}")' />
                    {% else %}
                    <input type="text" class="full-size"
                        value='[{{ file.title }}]({% get_media_prefix %}{{ file.path }})' />
                    {% endif %}
                </div>
            </aside>
        </article>
{% endblock %}