engine/configurations/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf import settings

from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [
    url(r'^', include("engine.pages.common.urls")),
    url(r'^channels/', include("engine.pages.channel.urls"))
]

if "static" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^pages/', include("engine.pages.static.urls")))

if "upload" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^files/', include("engine.pages.upload.urls")))

if "server" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^servers/', include("engine.pages.server.urls")))

if "game" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^games/', include("engine.pages.game.urls")))

if "calendar" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^calendar/', include("engine.pages.calendar.urls")))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/pages/common/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin

# Pebble
from engine.pages.common.views import AuthView
from engine.pages.common.views import CommonView

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [

    # ----------------------------------------
    #   Actions
    # ----------------------------------------

    url(r'^home/', include([
        url(r'^action/page/$',
            CommonView.page, name="action_home_page")
    ])),

    # ----------------------------------------
    #   Views
    # ----------------------------------------

    url(r'^$',
        CommonView.index, name="root"),

    url(r'^team/$',
        CommonView.team, name="team"),

    url(r'^profile/(?P<username>[^\s\/]+)/$',
        CommonView.profile, name="profile"),

    url(r'^uploads/avatar/(?P<uuid>[\w\d]+)/?$',
        CommonView.avatar, name="avatar"),

    url(r'^error/$',
        CommonView.index, name="error"),

    url(r'^home/(?P<page>[\d]+)/$',
        CommonView.index, name="home_page"),

    url(r'^settings/', include([

        # ----------------------------------------
        #   User preferences
        # ----------------------------------------

        url(r'^preferences/', include([
            url(r'^$',
                CommonView.preferences, name="preferences"),
            url(r'^(?P<option>[\w]+)/$',
                CommonView.preferences, name="option")
        ])),

        # ----------------------------------------
        #   Administration
        # ----------------------------------------

        url(r'^admin/',
            admin.site.urls)
    ])),

    url(r'^auth/', include([
        url(r'^register/$',
            AuthView.register, name="register"),
        url(r'^sign_in/$',
            AuthView.sign_in, name="sign_in"),
        url(r'^sign_out/$',
            AuthView.sign_out, name="sign_out"),
    ])),
]

engine/pages/common/models.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.db import models
from django.db.models.signals import post_save

from django.conf import settings

from django.dispatch import receiver

from django.contrib.auth.models import User

from django.core.files.storage import FileSystemStorage

# Filesystem
from os import remove

from pathlib import Path

# Pebble
from engine.common import is_allowed
from engine.common import get_mimetype

# ------------------------------------------------------------------------------
#   Functions
# ------------------------------------------------------------------------------

def upload_data(profile, filename):
    """ Upload an avatar

    This function define the user avatar file and replace the existing one

    Parameters
    ----------
    profile : user.models.Informations
        The user profile
    filename : str
        New avatar filename

    Returns
    -------
    str
        New avatar path in upload directory
    """

    mime = get_mimetype(profile.avatar.file)

    if is_allowed(mime):
        extension = settings.ALLOWED_AVATAR_EXTENSIONS[mime]

        try:
            from hashlib import blake2b

            name = blake2b(digest_size=32)

        except ImportError:
            from hashlib import sha256

            name = sha256()

        name.update(bytes(profile.user.username, "utf-8"))

        path = Path("avatar", "%s.%s" % (name.hexdigest(), extension))

        media_path = Path(settings.MEDIA_ROOT)

        if media_path.joinpath(path).exists():
            media_path.joinpath(path).unlink()

        return path

    return None


def get_themes():
    """ Retrieve available theme
    """

    theme_path = Path(settings.STATIC_DIR).joinpath("css", "themes")

    data = list()

    for filename in theme_path.glob("*.css"):
        data.append((filename.stem, filename.stem))

    return tuple(data)

# ------------------------------------------------------------------------------
#   Signals
# ------------------------------------------------------------------------------

@receiver(post_save, sender=User)
def on_post_save(sender, **kwargs):
    """ Generate informations model for new users

    This function generate the correct Informations model which is stack inside
    the default User model
    """

    if kwargs["created"]:
        kwargs["instance"].informations = Informations(pk=kwargs["instance"].pk)
        kwargs["instance"].informations.save()

# ------------------------------------------------------------------------------
#   Models
# ------------------------------------------------------------------------------

class Informations(models.Model):
    """ Represent user's informations
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    description = models.CharField(max_length=500, blank=True)

    jabber = models.EmailField(blank=True)
    email = models.EmailField(blank=True)

    diaspora = models.URLField(blank=True)
    mastodon = models.URLField(blank=True)
    website = models.URLField(blank=True)

    theme = models.CharField(
        max_length=64, default="default", choices=get_themes())

    avatar = models.ImageField(
        upload_to=upload_data, default="images/default.png")


    def __str__(self):
        """ Return model representation

        Returns
        -------
        str
            Model as string
        """

        return "%s's informations" % self.user.username


    @property
    def type(self):
        """ Return model type
        """

        return "informations"

templates/common/options/avatar.html
{% load utils i18n %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-user"></i>
                    {% trans 'Edit avatar' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'profile' user.username %}" title="{% trans 'Back to profile' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'preferences' %}" title="{% trans 'Edit parameters' %}">
                                <i class="fa fa-fw fa-cog"></i></a>
                        </li>
                        <li class="no-action">
                            <i class="fa fa-user"></i>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'informations' %}" title="{% trans 'Edit informations' %}">
                                <i class="fa fa-fw fa-vcard"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'password' %}" title="{% trans 'Edit password' %}">
                                <i class="fa fa-fw fa-key-modern"></i></a>
                        </li>
                    </ul>
                </nav>
            </header>

            {% if messages %}
            <aside class="banners">
                <ul class="messages">
                    {% for message in messages %}
                    <li>
                        <div{% if message.tags %} class="banner {{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </aside>
            {% endif %}

            <aside>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div>
                        <label>
                            <i class="fa fa-fw fa-user space"></i>{% trans 'Current avatar' %}
                        </label>
                        <div class="center">
                            <img class="avatar extra" src="{{ user.informations.avatar.url | avatar }}" />
                        </div>
                    </div>

                    <div>
                        <label for="id_new_avatar">
                            <i class="fa fa-fw fa-user-plus space"></i>{% trans 'New avatar' %}
                        </label>
                        <input type="file" name="new_avatar" required id="id_new_avatar" />
                    </div>

                    <footer>
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                    </footer>
                </form>
            </aside>
        </article>

templates/common/options/informations.html
{% load utils i18n %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-vcard"></i>
                    {% trans 'Edit informations' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'profile' user.username %}" title="{% trans 'Back to profile' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'preferences' %}" title="{% trans 'Edit parameters' %}">
                                <i class="fa fa-fw fa-cog"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'avatar' %}" title="{% trans 'Edit avatar' %}">
                                <i class="fa fa-fw fa-user"></i></a>
                        </li>
                        <li class="no-action">
                            <i class="fa fa-vcard"></i>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'password' %}" title="{% trans 'Edit password' %}">
                                <i class="fa fa-fw fa-key-modern"></i></a>
                        </li>
                    </ul>
                </nav>
            </header>

            {% if messages %}
            <aside class="banners">
                <ul class="messages">
                    {% for message in messages %}
                    <li>
                        <div{% if message.tags %} class="banner {{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </aside>
            {% endif %}

            <aside>
                <form method="post">
                    {% csrf_token %}

                    <div>
                        <label for="id_jabber">
                            <i class="fa fa-fw fa-xmpp space"></i>{% trans 'XMPP address' %}
                        </label>
                        <input type="email" name="jabber_informations" maxlength="254" id="id_jabber"
                            value="{{ user.informations.jabber }}" />
                    </div>

                    <div>
                        <label for="id_email">
                            <i class="fa fa-fw fa-envelope space"></i>{% trans 'Mail address' %}
                        </label>
                        <input type="email" name="email_informations" maxlength="254" id="id_email"
                            value="{{ user.informations.email }}" />
                    </div>

                    <div class="new-line">
                        <label for="id_website">
                            <i class="fa fa-fw fa-globe space"></i>{% trans 'Personnal website' %}
                        </label>
                        <input type="url" name="website_informations" maxlength="200" id="id_website"
                            value="{{ user.informations.website }}" />
                    </div>

                    <div>
                        <label for="id_diaspora">
                            <i class="fa fa-fw fa-diaspora space"></i>{% trans 'Diaspora account' %}
                        </label>
                        <input type="url" name="diaspora_informations" maxlength="200" id="id_diaspora"
                            value="{{ user.informations.diaspora }}" />
                    </div>

                    <div>
                        <label for="id_mastodon">
                            <i class="fa fa-fw fa-mastodon space"></i>{% trans 'Mastodon account' %}
                        </label>
                        <input type="url" name="mastodon_informations" maxlength="200" id="id_mastodon"
                            value="{{ user.informations.mastodon }}" />
                    </div>

                    <div class="new-line">
                        <label for="id_description">
                            <i class="fa fa-fw fa-book space"></i>{% trans 'Biography' %}
                        </label>
                        <textarea name="description_informations" cols="40" rows="10" maxlength="500" id="id_description">{{ user.informations.description }}</textarea>
                    </div>

                    <footer>
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                    </footer>
                </form>
            </aside>
        </article>

templates/common/options/parameters.html
{% load utils i18n %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-cog"></i>
                    {% trans 'Edit parameters' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'profile' user.username %}" title="{% trans 'Back to profile' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                        <li class="no-action">
                            <i class="fa fa-cog"></i>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'avatar' %}" title="{% trans 'Edit avatar' %}">
                                <i class="fa fa-fw fa-user"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'informations' %}" title="{% trans 'Edit informations' %}">
                                <i class="fa fa-fw fa-vcard"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'password' %}" title="{% trans 'Edit password' %}">
                                <i class="fa fa-fw fa-key-modern"></i></a>
                        </li>
                    </ul>
                </nav>
            </header>

            {% if messages %}
            <aside class="banners">
                <ul class="messages">
                    {% for message in messages %}
                    <li>
                        <div{% if message.tags %} class="banner {{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </aside>
            {% endif %}


            <aside>
                <form method="post">
                    {% csrf_token %}

                    <div>
                        <label for="id_theme">
                            <i class="fa fa-fw fa-paint-brush space"></i>{% trans 'Theme' %}
                        </label>
                        <select name="theme_parameters" id="id_theme">
                        {% for value, key in data %}
                            <option value="{{ value }}" {% if user.informations.theme|design == key %}selected{% endif %}>{{ key }}</option>
                        {% endfor %}
                        </select>
                    </div>

                    <footer>
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                    </footer>
                </form>
            </aside>
        </article>

templates/common/options/password.html
{% load utils i18n %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-key-modern"></i>
                    {% trans 'Edit password' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'profile' user.username %}" title="{% trans 'Back to profile' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'preferences' %}" title="{% trans 'Edit parameters' %}">
                                <i class="fa fa-fw fa-cog"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'avatar' %}" title="{% trans 'Edit avatar' %}">
                                <i class="fa fa-fw fa-user"></i></a>
                        </li>
                        <li class="custom-action">
                            <a href="{% url 'option' 'informations' %}" title="{% trans 'Edit informations' %}">
                                <i class="fa fa-fw fa-vcard"></i></a>
                        </li>
                        <li class="no-action">
                            <i class="fa fa-key-modern"></i>
                        </li>
                    </ul>
                </nav>
            </header>

            {% if messages %}
            <aside class="banners">
                <ul class="messages">
                    {% for message in messages %}
                    <li>
                        <div{% if message.tags %} class="banner {{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </aside>
            {% endif %}

            <aside>
                <form method="post">
                    {% csrf_token %}

                    <div>
                        <label for="id_current_password">
                            <i class="fa fa-fw fa-lock space"></i>{% trans 'Current password' %}
                        </label>
                        <input type="password" name="current_password" maxlength="200" id="id_current_password" />
                    </div>

                    <div class="new-line">
                        <label for="id_new_password">
                            <i class="fa fa-fw fa-unlock space"></i>{% trans 'New password' %}
                        </label>
                        <input type="password" name="new_password" maxlength="200" id="id_new_password" />
                    </div>

                    <div>
                        <label for="id_check_password">
                            <i class="fa fa-fw fa-check space"></i>{% trans 'Check new password' %}
                        </label>
                        <input type="password" name="check_password" maxlength="200" id="id_check_password" />
                    </div>

                    <footer>
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                    </footer>
                </form>
            </aside>
        </article>