engine/configurations/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf import settings

from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [
    url(r'^', include("engine.pages.common.urls")),
    url(r'^channels/', include("engine.pages.channel.urls"))
]

if "static" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^pages/', include("engine.pages.static.urls")))

if "upload" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^files/', include("engine.pages.upload.urls")))

if "server" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^servers/', include("engine.pages.server.urls")))

if "game" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^games/', include("engine.pages.game.urls")))

if "calendar" in settings.AVAILABLE_MODULES:
    urlpatterns.append(url(r'^calendar/', include("engine.pages.calendar.urls")))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engine/pages/server/urls.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.conf.urls import url
from django.conf.urls import include

# Pebble
from engine.pages.server.views import ServerView

# ------------------------------------------------------------------------------
#   Patterns
# ------------------------------------------------------------------------------

urlpatterns = [

    # ----------------------------------------
    #   Actions
    # ----------------------------------------

    url(r'^action/server/', include([
        url(r'^add/$',
            ServerView.add, name="action_server_add"),
        url(r'^edit/(?P<server_id>[\d]+)/$',
            ServerView.edit, name="action_server_edit"),
        url(r'^delete/(?P<server_id>[\d]+)/$',
            ServerView.delete, name="action_server_delete"),
        url(r'^page/$',
            ServerView.page, name="action_server_page")
        ])
    ),

    # ----------------------------------------
    #   Views
    # ----------------------------------------

    url(r'^$',
        ServerView.index, name="server_home"),

    url(r'^(?P<page>\d+)/$',
        ServerView.index, name="server_page"),

    url(r'^(?P<identifier>[^\s\/]+)-(?P<index>[\d]+)/$',
        ServerView.view, name="server_look")
]

engine/pages/server/models.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django.db import models

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator

from django.contrib.auth.models import User

# ------------------------------------------------------------------------------
#   Models
# ------------------------------------------------------------------------------

class Server(models.Model):

    type = "server"

    title = models.CharField(max_length=256)

    identifier = models.CharField(max_length=512)

    summary = models.CharField(max_length=256, blank=True)

    description = models.TextField(blank=True)

    ip_address = models.CharField(max_length=256, blank=True)
    port_address = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(65535)],
        blank=True, null=True)

    steam = models.BooleanField(default=False)

    private = models.BooleanField(default=False)
    sporadic = models.BooleanField(default=False)

    active = models.BooleanField(default=False)
    password = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="server_user")
    updater = models.ForeignKey(
        User, blank=True, null=True, related_name="server_updater")


    def __str__(self):
        """ Return model representation

        Returns
        -------
        str
            Model as string
        """

        return "%s (%s)" % (self.title, self.user.username)

engine/pages/server/views.py
# ------------------------------------------------------------------------------
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------

# Django
from django import forms

from django.conf import settings

from django.urls import reverse

from django.http import HttpResponseRedirect

from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext as _

# Pebble
from engine.common import generate_identifier

from engine.pages.channel.models import Channel
from engine.pages.server.models import Server

# ------------------------------------------------------------------------------
#   Forms
# ------------------------------------------------------------------------------

class ServerForm(forms.ModelForm):

    class Meta:

        model = Server

        fields = [
            "active",
            "user",
            "title",
            "summary",
            "description",
            "ip_address",
            "port_address",
            "steam",
            "private",
            "password",
            "sporadic"
        ]

# ------------------------------------------------------------------------------
#   Views
# ------------------------------------------------------------------------------

class ServerView(object):

    @login_required()
    def index(request, page=None):
        """ List available servers

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        page : int or None, optional
            Servers list paginator index
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        paginator = Paginator(Server.objects.order_by("-active", "title"),
            settings.PAGES["server"])

        # Load topics for specified page
        try:
            servers = paginator.page(page)

        except PageNotAnInteger as error:
            servers = paginator.page(1)

        except EmptyPage as error:
            servers = paginator.page(paginator.num_pages)

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "server/index.html", {
            "page": "servers",
            "user": login,
            "servers": servers
        })


    @login_required()
    def page(request):
        """ Move to a specific page

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        page = None

        if request.method == "POST":
            page = int(request.POST["page"])

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return HttpResponseRedirect(
            reverse("server_page", args=( page, )))


    @login_required()
    def view(request, identifier, index):
        """ View a specific server

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        identifier : str
            Server identifier
        index : int
            Server index
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        server = get_object_or_404(Server, pk=index)

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "server/view.html", {
            "page": "servers",
            "user": login,
            "server": server
        })


    @login_required()
    def add(request):
        """ Add a new server

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        if not login.has_perm("server.add_server"):
            return HttpResponseRedirect(reverse("error"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        if request.method == "POST":
            form = ServerForm(request.POST)

            if form.is_valid():

                # Generate channel identifier
                form.cleaned_data["identifier"] = generate_identifier(
                    form.cleaned_data["title"])

                form.cleaned_data["updater"] = login

                server = Server(**form.cleaned_data)
                server.save()

                return HttpResponseRedirect(reverse("server_look",
                    args=( server.identifier, server.pk )))

        else:
            form = ServerForm(initial={ "user": login.pk })

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "server/edit.html", {
            "page": "servers",
            "user": login,
            "form": form
        })


    @login_required()
    def edit(request, server_id):
        """ Edit an existing server

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        server_id : int
            Page primary key identifier
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        if not login.has_perm("server.change_server"):
            return HttpResponseRedirect(reverse("error"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        server = get_object_or_404(Server, pk=server_id)

        if not login.pk == server.user.pk:
            if not login.is_staff:
                return HttpResponseRedirect(reverse("error"))

        if request.method == "POST":
            form = ServerForm(request.POST)

            if form.is_valid():
                form.cleaned_data["updater"] = login

                for key, value in form.cleaned_data.items():
                    setattr(server, key, value)

                # Generate server identifier
                server.identifier = generate_identifier(server.title)

                server.save()

                return HttpResponseRedirect(reverse("server_look",
                    args=( server.identifier, server.pk )))

        else:
            form = ServerForm(instance=server)

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "server/edit.html", {
            "page": "servers",
            "user": login,
            "form": form,
            "server": server
        })


    @login_required()
    def delete(request, server_id):
        """ Delete an existing comment

        Parameters
        ----------
        request : django.core.handlers.wsgi.WSGIRequest
            Django request
        server_id : int
            Page primary key identifier
        """

        login = request.user

        if not login.is_active:
            return HttpResponseRedirect(reverse("sign_out"))

        if not login.has_perm("server.delete_server") or not login.is_staff:
            return HttpResponseRedirect(reverse("error"))

        # ----------------------------------------
        #   Request
        # ----------------------------------------

        server = get_object_or_404(Server, pk=server_id)

        if request.method == "POST":

            if request.POST["choice"] == "yes":
                # Remove server
                server.delete()

            return HttpResponseRedirect(reverse("server_home"))

        # ----------------------------------------
        #   Render
        # ----------------------------------------

        return render(request, "server/delete.html", {
            "page": "servers",
            "user": login,
            "server": server
        })

templates/server/delete.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} - {% trans 'Remove server' %} - {{ server.title }}{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-trash"></i>
                    {% trans 'Remove server' %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            <a href="{% url 'server_look' server.identifier server.pk %}" title="{% trans 'Back to server' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                        </li>
                    </ul>
                </nav>
            </header>

            <aside>
                <div class="banner warning">
                    {% blocktrans with title=server.title %}Are you sure to remove '{{ title }}' server ?{% endblocktrans %}
                </div>

                <form method="post" class="delete">
                    {% csrf_token %}

                    <div class="inline">
                        <input type="radio" id="radio_no" name="choice" value="no" checked="checked" />&nbsp;
                        <label class="left" for="radio_no">{% trans 'No' %}</label>
                    </div>

                    <div class="inline">
                        <input type="radio" id="radio_yes" name="choice" value="yes" />&nbsp;
                        <label class="left" for="radio_yes">{% trans 'Yes' %}</label>
                    </div>

                    <footer>
                        <input class="destructive-action" type="submit" value="{% trans 'Remove' %}" />
                    </footer>
                </form>
            </aside>
        </article>
{% endblock %}

templates/server/edit.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} -
    {% if server %}
        {% trans 'Edit server' %} - {{ server.title }}
    {% else %}
        {% trans 'New server' %}
    {% endif %}
{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    {% if server %}
                    <i class="fa fa-fw fa-edit"></i>
                    {% trans 'Edit server' %}
                    {% else %}
                    <i class="fa fa-fw fa-plus-square"></i>
                    {% trans 'New server' %}
                    {% endif %}
                </h1>

                <nav>
                    <ul>
                        <li>
                            {% if server %}
                            <a href="{% url 'server_look' server.identifier server.pk %}" title="{% trans 'Back to server' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                            {% else %}
                            <a href="{% url 'server_home' %}" title="{% trans 'Back to servers' %}">
                                <i class="fa fa-fw fa-arrow-left"></i></a>
                            {% endif %}
                        </li>
                    {% if server and perms.server.delete_server %}
                        {% if user.pk == server.user.pk or user.is_staff %}
                        <li class="destructive-action">
                            <a href="{% url 'action_server_delete' server.pk %}" title="{% trans 'Remove' %}">
                                <i class="fa fa-fw fa-remove"></i></a>
                        </li>
                        {% endif %}
                    {% endif %}
                    </ul>
                </nav>
            </header>

            <aside>
                <form method="post">
                    {% csrf_token %}

                    <div class="inline">
                        {{ form.active }}
                        <label for="id_active">{% trans 'Active' %}</label>
                    </div>

                    <div>
                        <label for="id_user">{% trans 'Maintainer' %}&nbsp;:</label>
                        {{ form.user }}
                    </div>

                    <div>
                        <label for="id_title">{% trans 'Title' %}&nbsp;:</label>
                        {{ form.title }}
                    </div>

                    <div>
                        <label for="id_summary">{% trans 'Summary' %}&nbsp;:</label>
                        {{ form.summary }}
                    </div>

                    <div>
                        <label for="id_description">{% trans 'Description' %}&nbsp;:</label>
                        {{ form.description }}
                    </div>

                    <div>
                        <label for="id_ip_address">{% trans 'Address' %}&nbsp;:</label>
                        {{ form.ip_address }}
                    </div>

                    <div>
                        <label for="id_port_address">{% trans 'Port' %}&nbsp;:</label>
                        {{ form.port_address }}
                    </div>

                    <div class="inline">
                        {{ form.private }}
                        <label for="id_private">{% trans 'Private' %}</label>
                    </div>

                    <div class="inline">
                        {{ form.password }}
                        <label for="id_password">{% trans 'Need password' %}</label>
                    </div>

                    <div class="inline">
                        {{ form.steam }}
                        <label for="id_steam">{% trans 'Available on Steam' %}</label>
                    </div>

                    <div class="inline">
                        {{ form.sporadic }}
                        <label for="id_sporadic">{% trans 'Sporadic' %}</label>
                    </div>

                    <footer>
                        {% if server %}
                        <input class="important" type="submit" value="{% trans 'Update' %}" />
                        {% else %}
                        <input class="important" type="submit" value="{% trans 'Create' %}" />
                        {% endif %}
                    </footer>
                </form>
            </aside>
        </article>
{% endblock %}

templates/server/index.html
{% extends "base.html" %}

{% load utils i18n %}

{% block title %} - {% trans 'Servers list' %}{% endblock %}

{% block main %}
        <article>
            <header>
                <h1>
                    <i class="fa fa-fw fa-server"></i>
                    {% trans 'Servers' %}
                </h1>

                {% if perms.server.add_server %}
                <nav>
                    <ul>
                        <li class="creative-action">
                            <a href="{% url 'action_server_add' %}" title="{% trans 'New server' %}">
                                <i class="fa fa-fw fa-plus"></i></a>
                        </li>
                    </ul>
                </nav>
                {% endif %}
            </header>

            {% if servers|length > 0 %}
            <aside class="table">
                {% for server in servers %}
                <div class="big">
                    <span>
                        {% if not server.active %}
                        <i class="fa fa-fw fa-close"></i>
                        {% elif server.sporadic %}
                        <i class="fa fa-fw fa-hourglass-half {% if server.private %}red{% else %}green{% endif %}"></i>
                        {% elif server.private %}
                        <i class="fa fa-fw fa-lock red"></i>
                        {% else %}
                        <i class="fa fa-fw fa-unlock-alt green"></i>
                        {% endif %}
                    </span>

                    <span class="full-size">
                        <a href="{% url 'server_look' server.identifier server.pk %}"
                            title="{{ server.summary }}">
                            {{ server.title }}
                        </a>
                    </span>

                    <span class="nowrap">
                        {% if server.ip_address %}
                        <i class="fa fa-fw fa-globe"></i>
                        <small>{{ server.ip_address }}{% if server.port_address %}&nbsp;:&nbsp;{{ server.port_address }}{% endif %}</small>
                        {% endif %}
                    </span>

                    <span>
                        {% if server.steam %}
                        <i class="fa fa-fw fa-steam-square" title="{% trans 'Available on Steam' %}"></i>
                        {% endif %}
                    </span>

                    <span>
                        <a href="{% url 'profile' server.user.username %}">
                            <img class="avatar big" title="{{ server.user.username }}"
                                src="{{ server.user.informations.avatar.url|avatar }}" />
                        </a>
                    </span>
                </div>
                {% endfor %}
            </aside>
            {% else %}
            <div class="banner warning">
                {% trans 'No server available' %}
            </div>
            {% endif %}
        </article>

        {% if servers.paginator.num_pages > 1 %}
        <nav class="pagination">
            <ul>
                <li>
                    {% if servers.has_previous %}
                    <a href="{% url 'server_page' 1 %}">
                        <i class="fa fa-chevron-left space"></i>{% trans 'First' %}
                    </a>
                    {% else %}
                    <div>
                        <i class="fa fa-chevron-left space"></i>{% trans 'First' %}
                    </div>
                    {% endif %}
                </li>
                <li>
                    {% if servers.has_previous %}
                    <a href="{% url 'server_page' servers.previous_page_number %}">
                        <i class="fa fa-caret-left space"></i>{% trans 'Previous' %}
                    </a>
                    {% else %}
                    <div>
                        <i class="fa fa-caret-left space"></i>{% trans 'Previous' %}
                    </div>
                    {% endif %}
                </li>
                <li class="selector">
                    <form action="{% url 'action_server_page' %}" method="post">
                        {% csrf_token %}

                        <label for="page">{% trans 'Move to page' %}</label>
                        <select name="page" id="page">
                            {% for index in servers.paginator.page_range %}
                            <option {% if index == servers.number %}selected="selected"{% endif %}
                                value="{{ index }}">{{ index }}</option>
                            {% endfor %}
                        </select>

                        <input type="submit" name="valid" value="Go" id="valid" />
                    </form>
                </li>
                <li>
                    {% if servers.has_next %}
                    <a href="{% url 'server_page' servers.next_page_number %}">
                        {% trans 'Next' %}<i class="fa fa-caret-right anti-space"></i>
                    </a>
                    {% else %}
                    <div>
                        {% trans 'Next' %}<i class="fa fa-caret-right anti-space"></i>
                    </div>
                    {% endif %}
                </li>
                <li>
                    {% if servers.has_next %}
                    <a href="{% url 'server_page' servers.paginator.num_pages %}">
                        {% trans 'Last' %}<i class="fa fa-chevron-right anti-space"></i>
                    </a>
                    {% else %}
                    <div>
                        {% trans 'Last' %}<i class="fa fa-chevron-right anti-space"></i>
                    </div>
                    {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
{% endblock %}

templates/server/sidebar.html
{% load utils i18n %}
                        <li {% if page == 'servers' %}class="active"{% endif %}>
                            <a href="{% url 'server_home' %}">
                                {% trans 'Servers' %}
                            </a>
                            {% if perms.server.add_server %}
                            <a href="{% url 'action_server_add' %}" title="{% trans 'Add server' %}">
                                <i class="fa fa-fw fa-plus creative-action"></i>
                            </a>
                            {% endif %}
                        </li>